name: pido
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  provider: ^6.0.1
  flutter_screenutil: ^5.0.0+2
  device_preview: ^1.0.0
  bot_toast: ^4.0.1
  dio: ^4.0.0
  email_validator: ^2.0.1
  url_launcher: ^6.0.7
  email_launcher: ^1.1.1
  image_picker: ^0.8.1+1
  flutter_html: ^2.1.0
  loading_animations: ^2.2.0
  tuple: ^2.0.0
  flutter_svg: ^0.23.0+1
  firebase_core:  
  firebase_messaging: ^11.2.3 
  shimmer: ^2.0.0
  simple_animations: ^4.0.1
  intl: ^0.17.0 
  # qr_code_scanner:  
  flutter_local_notifications: ^9.1.4
  location: ^4.3.0 
  geolocator: ^8.0.0
#  connectivity: ^0.4.9
  change_app_package_name: ^1.0.0
  cloud_firestore: 
  firebase_analytics: 
  google_maps_flutter: 
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.4.0
  #flutter_automation: 
  carousel_slider: ^4.0.0
  pull_to_refresh: ^2.0.0
  flutter_rating_bar: ^4.0.0
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.2.0
  syncfusion_flutter_sliders: ^19.2.44
  # google_mobile_ads: ^0.13.2
  timeago: ^3.1.0
  easy_localization: ^3.0.0
  webview_flutter: ^2.1.1
  flutter_exif_rotation: ^0.4.1
  photo_view: ^0.13.0
  cached_network_image: ^3.2.0
  printing: ^5.6.6
  infinite_scroll_pagination: ^3.1.0
  auto_size_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  flutter_native_splash: ^1.2.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  # android: true
  adaptive_icon_foreground: "assets/images/app-icon.png"
  adaptive_icon_background: "#E9D5E8"
  image_path: "assets/images/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
    - family: ArbFONTS-Hacen-Tunisia
      fonts:
      - asset: assets/fonts/ArbFONTS-Hacen-Tunisia.ttf
    - family: Caroline
      fonts:
      - asset: assets/fonts/Caroline.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:

  background_image: "assets/images/splash.png"
  
  