// ||... ar lang ...||
Map<String, String> ar = {
  'LoginInToYourAccount': 'تسجيل الدخول الى حسابك',
  'Email': 'البريد الالكتروني',
  'Password': 'كلمة المرور',
  'SignIn': 'تسجيل الدخول',
  'RegisterNew': 'تسجيل جديد',
  'ForgotPassword': 'هل نسيت كلمة المرور؟',
  "Don'tHaveAnAccount": "ليس لدك حساب؟",
  'Register': 'سجل',
  'Enter': 'دخول',
  'mustLogin':'للوصول الى هذه الصفحة يجب تسجيل الدخول',
  'Loading': 'جاري التحميل...',
  'ExitApp': 'اضغط مرة اخرى للخروج',

  'product_detail':'تفاصيل المنتج',
  'ThisFieldIsRequired': 'هذا الحقل مطلوب',
  'AllFieldsAreRequired': 'جميع الحقول مطلوبة',
  'ThisIsNotEmailFormat': 'هذا ليس صيغة بريد الكتروني',
  'EnterPassword': 'أدخل كلمة المرور',
  'EnterNewPassword': 'ادخل كلمة المرور الجديدة',
  'EnterEmail': 'أدخل البريد الالكتروني',
  'Skip': 'تخطي',
  'CreateNewAccount': 'انشاء حساب جديد',
  'Name': 'الاسم',
  'EnterFullName': 'ادخل اسمك الكامل',
  'MobileNumber': 'رقم الهاتف',
  'EnterMobileNumber': 'ادخل رقم الجوال',
  'City': 'المدينة',
  'ChooseACity': 'اختر المدينة',
   'ChooseADistrict': 'اختر المنطقة',
    'ChooseACompound': 'اختر المجمع',
    'ChooseABlock': 'اختر الحي',
        'ChooseLocationInMap': 'اختر العنوان على الخريطة',
    'ChooseLocation': 'اختر الموقع',
    'isDefault': 'الافتراضي',
    'NoStoresFound': 'لا يوجد متاجر',

  'ConfirmPassword': 'تاكيد كلمة المرور',
  'EnterConfirmPassword': 'اكد كلمة المرور',
  'ResetPassword': 'استعادة كلمة المرور',
  'Send': 'ارسال',
  'Home': 'الرئيسية',
  'Products': 'منتجات',
  'Offer': 'عرض',
  'AddToCart': 'اضافة الى السلة',
  'GoToCart': 'اذهب الى السلة',
  'Notifications': 'الاشعارات',
  'NoNotificationsFound': 'لا يوجد اشعارات !!',
  'NoSearchResults': 'لا يوجد نتائج',
  'Orders': 'الطلبات',
  'Status': 'الحالة',
  'OrderId': 'رقم الطلب',
  'Total': 'المجموع',
  'Favorite': 'المفضلة',
  'FavoriteIsEmpty': 'المفضلة فارغة',
  'NoProducts': 'لا يوجد منتجات',
  'Offers': 'العروض',
  'AboutUs': 'من نحن',
  'Settings': 'الاعدادات',
  'ChangeLanguage': 'تغيير اللغة',
  'ChangePassword': 'تغيير كلمة المرور',
  'EnterOldPassword': 'ادخل كلمة المرور القديمة',
  'ShareApp': 'مشاركة التطبيق',
  'TermsOfUse': 'شروط الاستخدام',
  'PrivacyPolicy': 'سياسة الخصوصية',
  'ContactUs': 'تواصل معنا',
  'ContactForm': 'صندوق التواصل',
  'Message': 'الرسالة',
  'ContactInformation': 'معلومات التواصل',
  'TapBackAgainToLeave': 'اضغط مرة اخرى للخروج',
  'SignOut': 'تسجيل الخروج',
  'Reviews': 'المراجعات',
  'Details': 'التفاصيل',
  'AverageRating': 'معدل التقييم',
  'WhatPeopleAreSaying': 'ماذا يقول المستخدمون :',
  'RelatedProducts': 'منتجات ذات صلة',
  'Quantity': 'الكمية',
  'Size': 'الحجم',
  'Views': 'مشاهدات',
  'Likes': 'اعجابات',
  'SAR': 'ريال',
  'SearchAboutProduct': 'ابحث عن منتج..',
  'Loading': 'الرجاء الانتظار...',
  'EnterMessage': 'ادخل الرسالة',
  'TypeAMessage': 'اكتب رسالة...',
  'Edit': 'تعديل',
  'EditProfile': 'تعديل الملف الشخصي',
  'Profile': 'الملف الشخصي',
  'PersonalInformation': 'المعلومات الشخصية',
  'Save': 'حفظ',
  'Failed': 'فشل',
  'Success': 'نجاح',
  'ChooseFrom': 'اختر من',
  'Gallery': 'المعرض',
  'Camera': 'الكاميرا',
  'SelectACity': 'اختر مدينة',
  'NoImagesAvailable': 'لا يوجد صور متاحة',
  'Coffee': 'كافي',
  'Salon': 'الصالون',
  'SeeAll': 'عرض الكل',
  'All': 'الكل',
  'Services': 'الخدمات',
  'VerifyMobile': 'تفعيل رقم الهاتف',
  'AgreeToTheTermsAndConditionsOfTheApp':
      'اوافق على الشروط والاحكام الخاصة بالتطبيق',
      
  'EnterThe4DigitCodeWeSentYouViaMobileToContinue':
      'ادخل الكود المكون من ٤ حقول الذي تم ارساله لك للاستمرار',
  'ResendCode': 'اعادة ارسال رمز التحقق',
  'ChangeTheNumber': 'تغير رقم الهاتف',
  'Continue': 'استمرار',
  'BeServiceProvider': 'كن مزود خدمة',
  'Bio': 'السيرة الذتية',
  'ServicesType': 'انواع الخدمات',
  'PleaseSelectOneOrMore': 'الرجاء اختيار واحدة او اكثر',
  'Cancel': 'الغاء',
  'Ok': 'موافق',
  'Address': 'العنوان',
  'NumberOfCars': 'عدد السيارات',
  'IdPhoto': 'صورة الهوية',
  'Change': 'تغيير',
  'CarLicensePhoto': 'صورة رخصة القيادة',
  'MyOffers': 'عروضي',
  'Active': 'فعال',
  'Expired': 'منتهي',
  'Completed': 'المكتملة',
  'Excluded': 'المستبعدة',
  'OfferId': 'رقم العرض',
  'Accept': 'قبول',
  'Username': 'اسم المستخدم',
  'Category': 'التصنيف',
  'Categories': 'التصنيفات',
  'CustomersOrders': 'طلبات الزبائن',
  'Providers': 'مزودين الخدمات',
  'Provider': 'مزود خدمة',
  'NoProvidersFound': 'لا يوجد مزودين خدمات',
  'MyOrders': 'طلباتي',
  'NewOrder': 'طلب جديد',
  'TypeYourOrderHere': 'اكتب تفاصيل طلبك هنا',
  'SelectAService': 'اختر خدمة',
  'AdditionalInformation': 'معلومات اضافية',
  'NumberOfPeople': 'عدد الاشخاص',
  'Date': 'التاريخ',
  'ServicesTypes': 'انواع الخدمات',
  'Menu': 'القائمة',
  'NumberOfOffers': 'عدد العروض',
  'OrderDetails': 'تفاصيل الطلب',
  'SubmitOffer': 'ارسال العرض',
  'Price': 'السعر',
  'NoOrdersFound': 'لا يوجد طلبات !',
  'NoOffersFound': 'لا يوجد عروض !',
  'Done': 'المكتملة',
  'ProfileIsUpToDate': 'الملف الشخصي محدث بالفعل',
  'PoweredByHexa': 'تم تطويره من قبل هكسا',
  'Search': 'البحث',
  'NoProvidersMatchTheSearch': 'لا يوجد مزودين متطابقين مع البحث',
  'Title': 'العنوان',
  'NoProvidersFoundSubTitle': 'لا يوجد مزودين خدمات بالتصنيف المختار',
  'YouMustAgreeToTheTerms': 'يجب ان توافق على شروط التطبيق',
  'Information': 'معلومات',
  'Images': 'الصور',
  'NoImagesFound': 'لا يوجد صور !!',
  'NoReviewsFound': 'لا يوجد مراجعات !!',
  'PressAddToAddImages': 'اضغط على زر الاضافة لاضافة صور جديدة',
  'MyCredentialsPhotos': 'الصور التوثيقية',
  'ChangeStatus': 'تغيير الحالة',
  'Available': 'متاح',
  'Busy': 'مشغول',
  'Description': 'الوصف',
  'UploadImageHere': 'ارفع الصورة هنا',
  'NoInternetConnection': 'لا يوجد اتصال بالانترنت',
  'IfYouHaveAnAccount': 'هل لديك حساب؟',
  'GoToOffer': 'اذهب الى العرض',
  'NoProductsFound': 'لا يوجد منتجات !!',
  'MyCart': 'السلة',
  'CartIsEmpty': 'السلة فارغة !!',
  'Checkout': 'الدفع',
  'MyWallet': 'محفظتي',
  'Gifts': 'الهدايا',
  'MyFavorite': 'المفضلة',
  'FAQ': 'الأسئلة الشائعة',
  'Logout': 'خروج',
  'LoggingOut': 'خروج',
  'ShipYourBalance': 'اشحن رصيدك',
  'AvailableBalance': 'الرصيد المتاح',
  'LastOperations': 'اّخر العمليات',
  'ShipBalance': 'شحن رصيد',
  'PullBalance': 'سحب رصيد',
  'NightSystem': 'النظام الليلي',
  'TechnicalSupport': 'الدعم الفني',
  'DiscountCode': 'كود الخصم',
  'Check': 'افحص',
  'SubTotal': 'المجموع الفرعي',
  'Discount': 'الخصم',
  'UrgentRequest': 'طلب مستعجل',
  'NumberOfScheduledTimes': 'عدد مرات الطلب المجدول',
  'NoAddressesFound': 'لا يوجد عناوين',
  'DeliveryPrice': 'سعر التوصيل',
  'Delivery': 'التوصيل',
  'Payment': 'الدفع',
  'Next': 'التالي',
  'Pay': 'ادفع',
  'YourWalletIsEmpty': 'محفظتك فارغة !!',
  'MobileMustBeAtLeast8Numbers':
      'رقم الهاتف يجب ان يتكون من ٨ خانات على الاقل',
  'OffTheTotal': 'من المجموع الكلي',
  'Filter': 'فلتر',
  'SortBy': 'ترتيب حسب',
  'Apply': 'تطبيق',
  'Clear': 'استعادة',
  'OrderStatus': 'حالة الطلب',
  'New': 'جديد',
  'Preparing': 'قيد التحضير',
  'OnDelivery': 'قيد التوصيل',
  'Urgent': 'عاجل',
  'Scheduled': 'مجدول',
  'HighToLow': 'الاعلى الى الأقل',
  'LowToHigh': 'الأقل الى الأعلى',
  'Recent': 'الأحدث',
  'Categories': 'التصنيفات',
  'PaymentMethod': 'طريقة الدفع',
  'DeliveryAddress': 'عنوان التوصيل',
  'DeliveryTime': 'وقت التوصيل',
  'DeliveryDate': 'تاريخ التوصيل',
  'Online': 'الكتروني',
  'Wallet': 'المحفظة',
      'Cash': 'عند الاستلام',
    'AddressName': 'اسم العنوان',

  'OrderCompleted': 'مكتمل',
  'SomethingWentWrong': 'عذرا لقد حدث خطأ ما !',
  'TryAgain': 'حاول مرة اخرى',
  'NoGiftsFound': 'لا يوجد هدايا !',
  'NoFaqFound': 'لا يوجد أسئلة شائعة !',
  'ThankYou': 'شكراً لك',
  'GoToHome': 'اذهب الى الرئيسية',
  'TrackDriver': 'تتبع السائق',
  'NoAddressFound': 'لا يوجد عنوان',
  'AddAddress': 'اضافة عنوان',
  'EmailNotExist': 'الايميل غير موجود',
  'RefreshCompleted': 'تم التحديث',
  'ThereIsNoDistricts': 'لا يوجد قطاعات',
  'ThereIsNoCompounds': 'لا يوجد مجمعات سكنية',
  'ThereIsNoBlocks': 'لا يوجد كتل سكانية',
  'ThankYouForRegisteringWithApplication':
      'شكراً لك على انشاء حساب جديد في تطبيق  نور',
  'YourRequestHasBeenAddedSuccessfully': 'تم ارسال طلبك بنجاح',
  'IWillReplyToYouTheFastestAvailableTime': 'سوف يتم الرد عليك بأسرع وقت',
  'ConfirmPasswordDoesNotMatchNewPassword':
      'تاكيد كلمة المرور لا تساوي كلمة المرور الجديدة',
        'YouCantAddItemFromAnotherStore': 'لا يمكن اضافة منتجات من متجر اخر',
  'ClearCart': 'هل تريد افراغ السلة والشراء من هذا المتجر',
  'CleartheCart': 'افراغ',
  'SignInWithPhoneNumber': 'قم بتسجيل الدخول باستخدام \n رقم الجوال',
  'SendVerificationCode': 'ارسل رمز التحقق',
    'TermAndConditions': 'الشروط والاحكام',
    'ConfirmVerificationCode': 'تاكيد رمز التحقق',
    'Confirm': 'تأكيد',
    'VerificationCode': 'رمز التحقق',
     'Male': 'ذكر',
    'Female': 'انثى',
    'AppName': 'مشمش',
    'EnterPhoneNumberAndWeWillSendVerificationCode': 'الرجاء إدخال رقم هاتفك أدناه وسنرسل لك رمز التوثيق',
    'EnterVerificationCode': 'أدخل رمز التوثيق',
    'EnterVerificationOf4Digits': ' أدخل رمز توثيق يتكون من 4 ارقام',
    'Verify': 'توثيق',
    'SearchText': 'نص البحث',
    'CityWordEtc': 'كلمة,مدينة,الخ',
    'MainCategory': 'التصنيف الرئيسي',
    'SubCategory': 'التصنيف الفرعي',
    'Age': 'الفئة العمرية',
    'Sex': 'الجنس',
    'EducationEnviroment': 'البيئة التعليمية',
    'Time': 'الوقت',
    'SearchResults': 'نتائج البحث',
    'SearchForCategory': 'بحث عن تصنيف',
    'MyServices': 'خدماتي',
    'Explore': 'اكتشف',
    'Messages': 'الرسائل',
    'HadNotReciveVerificationCode': 'اذا لم تتلق رسالة نصية تحتوي على رمز التوثيق, انقر على اعادة الارسال',
    
    'NearBy': 'القريب',
    'MyCity': 'مدينتي',
    'AddService': 'اضافة خدمة',
    'YouHaveBeenReachedTheMaximumNumberOfServices': 'لقد وصلت إلى حد أقصى لاضافة خدمات',
    'ToAddMoreSubsicribeWithTheProEdition': 'لاضافة خدمات اخرى, اشترك في النسخة الاحترافية ',
    'MyProfile': 'حسابي',
    'LocationAndAddress': 'الموقع والعنوان',
    'NoAdsVersion': 'نسخة خالية من الاعلانات',
    'AppAndSupport': 'التطبيق والدعم',




};
