// ||... en lang ...||
Map<String, String> en = {
  'LoginInToYourAccount': 'Login in to your account',
  'Email': 'Email',
  'Password': 'Password',
  'SignIn': 'Login',
    'RegisterNew': 'Register',

  'ExitApp': 'Press again to exit',

  'Enter': 'Sign in',
  'ForgotPassword': 'Forgot Password?',
  "Don'tHaveAnAccount": "Don't have an account",
    'product_detail':'Product Detail',
'mustLogin':'To access this page you have to login',
  'Register': 'Register',
  'ThisFieldIsRequired': 'This field is required',
  'AllFieldsAreRequired': 'All fields are required',
  'EnterPassword': 'Enter password',
  'EnterNewPassword': 'Enter new password',
  'EnterEmail': 'Enter email address',
  'ThisIsNotEmailFormat': 'This is not email format',
  'Skip': 'Skip',
  'CreateNewAccount': 'Create New Account',
  'Name': 'Name',
  'EnterFullName': 'Enter full name',
  'MobileNumber': 'Mobile Number',
  'EnterMobileNumber': 'Enter mobile number',
  'City': 'City',
  'ChooseACity': 'Choose a city',
    'ChooseLocationInMap': 'Select Location In Map',
    'ChooseLocation': 'Select Location ',
    'isDefault': 'Default',

    'ChooseADistrict': 'Choose a district',
    'ChooseACompound': 'Choose a compound',
    'ChooseABlock': 'Choose a Block',

  'ConfirmPassword': 'Confirm Password',
  'EnterConfirmPassword': 'Enter confirm password',
  'ResetPassword': 'Reset Password',
  'Send': 'Send',
  'Home': 'Home',
  'Products': 'Products',
  'Offer': 'Offer',
  'AddToCart': 'Add To Cart',
  'GoToCart': 'Go To Cart',
  'Notifications': 'Notifications',
  'NoNotificationsFound': 'No Notifications found !!',
  'Orders': 'Orders',
  'Status': 'Status',
  'OrderId': 'Order Id',
  'Total': 'Total',
  'Favorite': 'Favorite',
  'FavoriteIsEmpty': 'Favorite Is Empty',
  'NoProducts': 'No Products',
  'Offers': 'Offers',
  'AboutUs': 'About us',
  'Settings': 'Settings',
  'ChangeLanguage': 'Change Language',
  'ChangePassword': 'Change Password',
  'EnterOldPassword': 'Enter old password',
  'ShareApp': 'Share App',
  'TermsOfUse': 'Terms Of Use',
  'PrivacyPolicy': 'Privacy Policy',
  'ContactUs': 'Contact Us',
  'ContactForm': 'Contact Form',
  'ContactInformation': 'Contact Information',
  'Message': 'Message',
  'TapBackAgainToLeave': 'Tap back again to leave',
  'SignOut': 'Sign Out',
  'Reviews': 'Reviews',
  'Details': 'Details',
  'AverageRating': 'Average Rating',
  'WhatPeopleAreSaying': 'What people are saying',
  'RelatedProducts': 'Related Products',
  'Quantity': 'Quantity',
  'Size': 'Size',
  'Views': 'Views',
  'Likes': 'Likes',
  'SAR': 'SAR',
  'SearchAboutProduct': 'Search about product...',
  'NoSearchResults': 'No Search Results',
  'Loading': 'Loading...',
  'EnterMessage': 'Enter Message',
  'TypeAMessage': 'Type a message...',
  'Edit': 'Edit',
  'EditProfile': 'Edit Profile',
  'Profile': 'Profile',
  'PersonalInformation': 'Personal Information',
  'Save': 'Save',
  'Failed': 'Failed',
  'Success': 'Success',
  'ChooseFrom': 'Choose From',
  'Gallery': 'Gallery',
  'Camera': 'Camera',
  'SelectACity': 'Select a city',
  'NoImagesAvailable': 'No images available',
  'Coffee': 'Coffee',
  'Salon': 'Salon',
  'SeeAll': 'See all',
  'All': 'All',
  'Services': 'Services',
  'VerifyMobile': 'Verify Mobile',
  'AgreeToTheTermsAndConditionsOfTheApp':
      'Agree to the terms and conditions of the app',
  'EnterThe4DigitCodeWeSentYouViaMobileToContinue':
      'Enter the 4 digit code we sent you via Mobile to continue',
  'ResendCode': 'Resend Code',
  'ChangeTheNumber': 'Change The Number',
  'Continue': 'Continue',
  'BeServiceProvider': 'Be Service Provider',
  'Bio': 'Bio',
  'ServicesType': 'Services Type',
  'PleaseSelectOneOrMore': 'Please select one or more',
  'Cancel': 'CANCEL',
  'Ok': 'OK',
  'Address': 'Address',
  'NumberOfCars': 'Number Of Cars',
  'IdPhoto': 'Id Photo',
  'Change': 'Change',
  'CarLicensePhoto': 'Car License Photo',
  'MyOffers': 'My Offers',
  'Active': 'Active',
  'Expired': 'Expired',
  'Completed': 'Completed',
  'Excluded': 'Excluded',
  'OfferId': 'Offer Id',
  'Accept': 'Accept',
  'Username': 'Username',
  'Category': 'Category',
  'Categories': 'Categories',
  'CustomersOrders': 'Customers Orders',
  'Providers': 'Providers',
  'Provider': 'Provider',
  'NoProvidersFound': 'No Providers Found',
  'MyOrders': 'My Orders',
  'NewOrder': 'New Order',
  'TypeYourOrderHere': 'Type your order here',
  'SelectAService': 'Select a service',
  'AdditionalInformation': 'Additional Information',
  'NumberOfPeople': 'Number of people',
  'Date': 'Date',
  'ServicesTypes': 'Services Types',
  'Menu': 'Menu',
  'NumberOfOffers': 'Number of offers',
  'OrderDetails': 'Order Details',
  'SubmitOffer': 'Submit Offer',
  'Price': 'Price',
  'NoOrdersFound': 'No orders found !',
  'NoOffersFound': 'No offers found !',
  'Done': 'Done',
  'ProfileIsUpToDate': 'Profile is up to date',
  'PoweredByHexa': 'Powered by Hexa',
  'Search': 'Search',
  'NoProvidersMatchTheSearch': 'No providers match the search',
  'ConfirmPasswordDoesNotMatchNewPassword':
      'Confirm password does not match new password',
  'Title': 'Title',
  'YouMustAgreeToTheTerms': 'You must agree to the terms',
  'Information': 'Information',
  'Images': 'Images',
  'NoImagesFound': 'No images found !!',
  'NoReviewsFound': 'No reviews Found !!',
  'PressAddToAddImages': 'Press add to add images',
  'MyCredentialsPhotos': 'My Credentials Photos',
  'ChangeStatus': 'Change Status',
  'Available': 'Available',
  'Busy': 'Busy',
  'Description': 'Description',
  'UploadImageHere': 'Upload image here',
  'NoInternetConnection': 'No Internet Connection',
  'IfYouHaveAnAccount': 'If You Have An account?',
  'GoToOffer': 'Go To Offer',
  'NoProductsFound': 'No Products Found !!',
    'NoStoresFound': 'No Stores Found !!',

  'CartIsEmpty': 'Cart Is Empty',
  'MyCart': 'My Cart',
  'Checkout': 'Checkout',
  'MyWallet': 'My Wallet',
  'Gifts': 'Gifts',
  'MyFavorite': 'My Favorite',
  'FAQ': 'FAQ',
  'Logout': 'Logout',
  'LoggingOut': 'Logging out',
  'ShipYourBalance': 'Ship Your balance',
  'AvailableBalance': 'Available Balance',
  'LastOperations': 'Last Operations',
  'ShipBalance': 'Ship balance',
  'PullBalance': 'Pull balance',
  'NightSystem': 'Night System',
  'TechnicalSupport': 'Technical Support',
  'DiscountCode': 'Discount Code',
  'Check': 'Check',
  'SubTotal': 'Sub Total',
  'Discount': 'Discount',
  'UrgentRequest': 'Urgent Request',
  'NumberOfScheduledTimes': 'Number of scheduled times',
  'NoAddressesFound': 'No Addresses found',
  'DeliveryPrice': 'Delivery price',
  'Delivery': 'Delivery',
  'Payment': 'Payment',
  'Next': 'Next',
  'Pay': 'Pay',
  'YourWalletIsEmpty': 'Your Wallet is empty !!',
  'MobileMustBeAtLeast8Numbers': 'Mobile must be at least 8 numbers',
  'OffTheTotal': 'off the total',
  'Filter': 'Filter',
  'SortBy': 'Sort by',
  'Apply': 'Apply',
  'Clear': 'Clear',
  'OrderStatus': 'Order status',
  'New': 'New',
  'Preparing': 'Preparing',
  'OnDelivery': 'On Delivery',
  'Urgent': 'Urgent',
  'Scheduled': 'Scheduled',
  'PaymentMethod': 'Payment Method',
  'HighToLow': 'High To Low',
  'LowToHigh': 'Low To High',
  'Recent': 'Recent',
  'DeliveryAddress': 'Delivery Address',
  'DeliveryTime': 'Delivery Time',
  'DeliveryDate': 'Delivery Date',
  'Online': 'Online',
    'Cash': 'Cash',
    'AddressName': 'Address Name',

  'Wallet': 'Wallet',
  'OrderCompleted': 'Completed',
  'SomethingWentWrong': 'Something Went Wrong !',
  'TryAgain': 'Try Again',
  'NoGiftsFound': 'No Gifts Found !',
  'NoFaqFound': 'No Faq Found !',
  'ThankYou': 'Thank You',
  'GoToHome': 'Go To Home',
  'TrackDriver': 'Track Driver',
  'NoAddressFound': 'No Address Found',
  'RefreshCompleted': 'Refresh Completed',
  'AddAddress': 'Add Address',
  'ThereIsNoDistricts': 'There Is No Districts',
  'ThereIsNoCompounds': 'There Is No Compounds',
  'ThereIsNoBlocks': 'There Is No BLocks',
  'EmailNotExist': 'Email Not Exist',
  'IWillReplyToYouTheFastestAvailableTime':
      'I Will Reply To You The Fastest Available Time',
  'YourRequestHasBeenAddedSuccessfully':
      'Your request has been added successfully',
  'ThankYouForRegisteringWithApplication':
      'Thank You For Registering With Noor Delivery Application',
  'NoProvidersFoundSubTitle':
      'There is no service providers with this category',
        'YouCantAddItemFromAnotherStore': 'You Cant Add Item From Another Store',
          'ClearCart': 'Do You Want To Clear Cart And Start Add Items From This Store',
  'CleartheCart': 'Clear',
  'SignInWithPhoneNumber': 'Sign In With Phone Number',
    'SendVerificationCode': 'Send Verification Code',
    'TermAndConditions': 'Term And Conditions',
    'ConfirmVerificationCode': 'Confirm Verification Code',
    'Confirm': 'Confirm',
    'VerificationCode': 'Verification Code',
    'Male': 'Male',
    'Female': 'Female',
    'AppName': 'MshMsh',
    'EnterPhoneNumberAndWeWillSendVerificationCode': 'Enter Phone Number And We Will Send Verification Code',
    'EnterVerificationOf4Digits': 'Ente rVerification Code Of 4 Digits',
    'Verify': 'Verify',
'SearchText': 'Search Text',
    'CityWordEtc': 'City, Word,etc',
    'MainCategory': 'Main Category',
    'SubCategory': 'Sub Category',
    'Age': 'Age',
    'Sex': 'Sex',
    'EducationEnviroment': 'Education Enviroment',
    'Time': 'Time',
'SearchResults': 'Search Results',
    'SearchForCategory': 'Search For Category',
    'MyServices': 'My Services',
    'Explore': 'Explore',
    'Messages': 'Messages',
    'HadNotReciveVerificationCode': 'If You Had Not Recive Verification Code, click ReSend Code',
 'NearBy': 'Near By',
    'MyCity': 'My City',
    'AddService': 'Add Service',
    'YouHaveBeenReachedTheMaximumNumberOfServices': 'You Have Been Reached The Maximum Number Of Services',
    'ToAddMoreSubsicribeWithTheProEdition': 'To Add More Subsicribe With The Pro Edition',
    'MyProfile': 'My Profile',
    'LocationAndAddress': 'Location And Address',
    'NoAdsVersion': 'No Ads Version',
    'AppAndSupport': 'App And Support',
};
