// ||... ar lang ...||
Map<String, String> tr = {
  'LoginInToYourAccount': 'hesaba giriş yap',
  'Email': 'E-Posta',
  'Password': 'şifre',
  'SignIn': "giriş yap",
  'ForgotPassword': 'şifreyı unuttun mu?',
  "Don'tHaveAnAccount": "hesabın yok mu ?",
  'Register': 'hesap oluştur',
  'Enter': 'giriş',
  'ThisFieldIsRequired': 'bu alan gereklidir',
  'ThisIsNotEmailFormat': 'هذا ليس صيغة بريد الكتروني',
  'product_detail': 'ürün ayrıntısı',
  'mustLogin': 'Bu sayfaya erişmek için giriş yapmalısınız',
  'Loading': 'Yükleniyor...',
  'ExitApp': 'Çıkmak için tekrar basın',
  'Cash': 'nakit',
  'AddressName': 'adres adı',
  'EnterPassword': 'şifre gir',
  'EnterNewPassword': 'yeni şifre gir',
  'EnterEmail': 'E-postayı girin',
  'Skip': 'geç',
  'CreateNewAccount': 'yeni hesap oluştur',
  'Name': 'Ad',
  'EnterFullName': 'Ad soyad',
  'MobileNumber': 'elefon no',
  'EnterMobileNumber': 'elefon no gir',
  'City': 'şehir',
  'ChooseACity': 'şehir seç',
  'ChooseADistrict': 'bir bölge seçin',
  'ChooseACompound': 'Bir bileşik seçin',
  'ChooseABlock': 'Bir Blok Seçin',
  'ChooseLocationInMap': 'Haritada Konum Seçin',
  'ChooseLocation': 'Yer Seçiniz',
      'isDefault': 'Varsayılan',
    'NoStoresFound': 'Mağaza Bulunamadı !!',

  'ConfirmPassword': 'şifreyi onayla',
  'EnterConfirmPassword': 'şifreyi onaylayın',
  'ResetPassword': 'parola yenile',
  'Send': 'gönder',
  'Home': 'ana sayfa',
  'Products': 'ürünler',
  'Offer': 'göster',
  'AddToCart': 'sebete ekle',
  'Notifications': 'bildirimler',
  'NoNotificationsFound': 'bildirimler yok !!',
  'NoSearchResults': 'sonuç bulunmadı',
  'Orders': 'siparişler',
  'Status': 'durum',
  'OrderId': 'sipariş no',
  'Total': 'toplam',
  'Favorite': 'favori',
  'FavoriteIsEmpty': 'favori boş',
  'NoProducts': 'ürün bulunmad',
  'Offers': 'teklifler',
  'AboutUs': 'biz kim?',
  'Settings': 'ayarlar',
  'ChangeLanguage': 'dili değiştir',
  'ChangePassword': 'şifreyi değiştir',
  'EnterOldPassword': 'eski şifreyi gir',
  'ShareApp': 'uygulamayı paylaş',
  'TermsOfUse': 'kullanıım şartları',
  'PrivacyPolicy': 'gizlilik politikası',
  'ContactUs': 'bizimle iletişime geçin',
  'ContactForm': 'iletişim kutusu',
  'Message': 'mesajlar',
  'ContactInformation': 'iletişim bilgileri',
  'TapBackAgainToLeave': 'çıkmak için tekrer tıklayınız',
  'SignOut': 'çikiş yap',
  'Reviews': 'detaylar',
  'Details': 'Ayrıntılar',
  'AverageRating': 'Değerlendirme',
  'WhatPeopleAreSaying': 'kullanıcılar ne diyorlar:',
  'RelatedProducts': 'benzer',
  'Quantity': 'miktar',
  'Size': 'hacim',
  'Views': 'izlenmeler',
  'Likes': 'beğenmeler',
  'SAR': 'riyal',
  'SearchAboutProduct': 'ürün ara ..',
  'Loading': 'lütfen bekleyeniz..',
  'EnterMessage': 'mesaj gir',
  'TypeAMessage': 'mesaj yaz...',
  'Edit': 'ayarla',
  'EditProfile': 'kişisel profili ayarla',
  'Profile': 'kişisel profil',
  'PersonalInformation': 'kişisel bilgiler',
  'Save': 'kaydet',
  'Failed': 'başarsız',
  'Success': 'başarı',
  'ChooseFrom': 'seç',
  'Gallery': 'galeri',
  'Camera': 'kamera',
  'SelectACity': 'şehir seç',
  'NoImagesAvailable': 'otoğraf bulunmadı',
  'Coffee': 'yeter',
  'Salon': 'Salon',
  'SeeAll': 'hepsini göster',
  'All': 'herşey',
  'Services': 'hizmetler',
  'VerifyMobile': 'telefon no aktif et',
  'AgreeToTheTermsAndConditionsOfTheApp':
      'Başvurunun hüküm ve koşullarını kabul ediyorum',
  'EnterThe4DigitCodeWeSentYouViaMobileToContinue':
      'devam etmek için 4 rakamdan oluşan kod gir',
  'ResendCode': 'kodu yineden gönder',
  'ChangeTheNumber': 'telefon no değiştir',
  'Continue': 'devam',
  'BeServiceProvider': 'servis çeşitleri',
  'Bio': 'lütfen bir veya birden fazla seçeniz',
  'ServicesType': 'iptal',
  'PleaseSelectOneOrMore': 'lütfen bir veya birden fazla seçeniz',
  'Cancel': 'iptal',
  'Ok': 'onaylıyorum',
  'Address': 'adres',
  'NumberOfCars': 'araç sayısı',
  'IdPhoto': 'Kimlik fotoğrafı',
  'Change': 'değiştir',
  'CarLicensePhoto': 'Sürücü belgesinin bir kopyası',
  'MyOffers': 'tekliflerim',
  'Active': 'aktif',
  'Expired': 'bitmiş',
  'Completed': 'tamamlanan',
  'Excluded': 'Hariç tutuldu',
  'OfferId': 'teklif no',
  'Accept': 'onaylamak',
  'Username': 'kullanıcı adı',
  'Category': 'kategori',
  'CustomersOrders': 'müşterilern siparişleri',
  'Providers': 'siparişlerim',
  'Provider': 'مزود خدمة',
  'NoProvidersFound': 'لا يوجد مزودين خدمات',
  'MyOrders': 'siparişlerim',
  'NewOrder': 'Yeni istek',
  'TypeYourOrderHere': 'اكتب تفاصيل طلبك هنا',
  'SelectAService': 'اختر خدمة',
  'AdditionalInformation': 'ek bilgiler',
  'NumberOfPeople': 'insanların sayısı',
  'Date': 'tarih',
  'ServicesTypes': 'servis çeşitleri',
  'Menu': 'liste',
  'NumberOfOffers': 'teklıf sayısı',
  'OrderDetails': 'sipariş detayları',
  'SubmitOffer': 'eklifi gönder',
  'Price': 'fiyat',
  'NoOrdersFound': 'sipariş bulunmadı!',
  'NoOffersFound': 'teklif bulunmadı !',
  'Done': 'tamamlanan',
  'ProfileIsUpToDate': 'kişisel profil güncenllendi',
  'PoweredByHexa': 'تم تطويره من قبل هكسا',
  'Search': 'Arama',
  'NoProvidersMatchTheSearch': 'لا يوجد مزودين متطابقين مع البحث',
  'Title': 'adres',
  'NoProvidersFoundSubTitle': 'لا يوجد مزودين خدمات بالتصنيف المختار',
  'YouMustAgreeToTheTerms': 'uygulama koşulları onaylanmalıdır',
  'Information': 'bilgiler',
  'Images': 'fotoğraflar',
  'NoImagesFound': 'fotoğraf bulunmadı!!',
  'NoReviewsFound': 'inceleme bulunmadı !!',
  'PressAddToAddImages': 'yeni fotoğraf eklemek için ekle tıklayınız',
  'MyCredentialsPhotos': 'belgesel fotoğraflar',
  'ChangeStatus': 'durumu değiştir',
  'Available': 'mevcut',
  'Busy': 'meşgul',
  'Description': 'tanım',
  'UploadImageHere': 'fotoğrafı burda yükleyiniz',
  'NoInternetConnection': 'nternet bağıntı yok',
  'IfYouHaveAnAccount': 'hesabın var mı?',
  'OrderNow': 'şimdi sipariş ver',
  'NoProductsFound': 'ürün bulunmadı !!',
  'MyCart': 'sebet',
  'CartIsEmpty': 'sebet boş !!',
  'Checkout': 'ödeme',
  'MyWallet': 'cuzdanım',
  'Gifts': 'hediyeler',
  'MyFavorite': 'favori',
  'FAQ': 'yaygın sorular',
  'Logout': 'çıkış',
  'LoggingOut': 'çık',
  'ShipYourBalance': 'bakiyeniz yükleyin',
  'AvailableBalance': 'bakiye varıkları',
  'LastOperations': 'son işlemler',
  'ShipBalance': 'Bakiyenizi yeniden doldurun',
  'PullBalance': 'Bakiye çekme',
  'NightSystem': 'koyu mod',
  'TechnicalSupport': 'teknik destek',
  'DiscountCode': 'ndirim kodu',
  'Check': 'kontrol',
  'SubTotal': 'ara toplam',
  'Discount': 'indirim',
  'UrgentRequest': 'acil sipariş',
  'NumberOfScheduledTimes': 'Planlanan isteğin sayısı',
  'NoAddressesFound': 'adres bulunmadı',
  'DeliveryPrice': 'kargo fiyatı',
  'Delivery': 'kargo',
  'Payment': 'ödeme',
  'Next': 'sonraki',
  'Pay': 'ödeme yap',
  'YourWalletIsEmpty': 'cuzdanınız boş!!',
  'MobileMustBeAtLeast8Numbers': 'telefon no en az 8 rakamdan olmalıdır',
  'OffTheTotal': 'toplamdan',
  'Filter': 'filtre',
  'SortBy': 'göre düzenle',
  'Apply': 'uygulama',
  'Clear': 'geri almak',
  'OrderStatus': 'sipariş durumu',
  'New': 'yeni',
  'Preparing': 'hazırlık aşamasındadır',
  'OnDelivery': 'kargo aşamasındadır',
  'Urgent': 'acil',
  'Scheduled': 'Planlandı',
  'HighToLow': 'yüksekten düşüğe',
  'LowToHigh': 'düşükten yükseğe',
  'Recent': 'en son',
  'Categories': 'kategoriler',
  'PaymentMethod': 'ödeme yöntemi',
  'DeliveryAddress': 'teslim adres',
  'DeliveryTime': 'eslim zamanı',
  'DeliveryDate': 'teslim tarihi',
  'Online': 'elektronik',
  'Wallet': 'cuzdan',
  'OrderCompleted': 'tamamlandı',
  'SomethingWentWrong': 'üzgünüz bir hata oldu !',
  'TryAgain': 'tekrar deneyeniz',
  'NoGiftsFound': 'hediye bulunmadı !',
  'NoFaqFound': 'yaygın sorular bulunmadı !',
  'ThankYou': 'sizlere teşekkür ediyoruz',
  'GoToHome': 'ana sayfayı git',
  'TrackDriver': 'kargoyu takip edin',
  'NoAddressFound': 'başlık bulunmadı',
  'AddAddress': 'Başlık ekle',
  'RefreshCompleted': 'Yenileme Tamamlandı',
  'ThankYouForRegisteringWithApplication':
      'Noor Delivery uygulamısında hesap oluşturduğunuz için teşekkür ederiz',
  'YourRequestHasBeenAddedSuccessfully': 'isteğiniz başarlı gönderildi',
  'IWillReplyToYouTheFastestAvailableTime': 'en kısa zamanda cevap verilecek',
  'ConfirmPasswordDoesNotMatchNewPassword':
      'şifreyi onaylayın yeni şifreyi eşleşmiyor',
         'YouCantAddItemFromAnotherStore': 'Başka Bir Mağazadan Ürün Ekleyemezsiniz',
          'ClearCart': 'Sepeti Temizleyip Bu Mağazadan Ürün Eklemeye Başlamak İster misiniz?',
  'CleartheCart': 'Açık',

};
